version: "3"
services:
    front:
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        build:
            context: ./client
        ports:
            - 3000:3000
        volumes:
            - /app/node_modules
            - ./client:/app
    
    back:
        stdin_open: true
        build:
            context: ./server
        ports: 
            - 5000:5000
        volumes:
            - /app/node_modules
            - ./server:/app
    db:
        image: 'mongo'
        ports:
            - 27017:27017
        environment:
            - MONGOMS_SYSTEM_BINARY=/usr/bin/mongod
        volumes:
            - './mongo:/data/db'